# Generated by Django 4.1.1 on 2022-12-13 04:09

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "vendor_code",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Артикул"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=11,
                        null=True,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "В наличии"),
                            (2, "Под заказ"),
                            (3, "Ожидается поступление"),
                            (4, "Нет в наличии"),
                            (5, "Не производится"),
                        ],
                        default=1,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "img",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="WEBP",
                        keep_meta=True,
                        quality=75,
                        scale=None,
                        size=[1920, 1080],
                        upload_to="photos/%Y/%m/%d",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "extension",
                    models.CharField(
                        blank=True, max_length=8, verbose_name="Доступный формат"
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["title"],
            },
        ),
    ]
